---
services:
  opentakserver:
    image: opentakserver:latest
    build:
      context: .
      args:
        - BUILD_VERSION=${BUILD_VERSION}
      tags:
        - opentakserver:${BUILD_VERSION}
        - opentakserver:latest
    container_name: opentakserver
